name: Linux

on:
  pull_request: null
  workflow_dispatch:
    inputs:
      myCommit:
        description: Commit SHA1
        required: false
        default: ''
        type: string
      releaseTag:
        description: Release tag
        required: false
        default: ''
        type: string
  workflow_call:
    inputs:
      myCommit:
        description: Commit SHA1
        required: false
        default: ''
        type: string
      releaseTag:
        description: Release tag
        required: false
        default: ''
        type: string
  push: null
  release:
    types:
      - published

# cancels currently running workflow from the same PR, branch or tag
#concurrency:
#  group: ${{github.workflow}}-${{github.ref}}
#  cancel-in-progress: true

jobs:
  build_linux:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Release
        architecture:
          - x86
          - x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: '${{inputs.myCommit}}'

      - name: Configure
        run: |
            sh autogen.sh
            ls
            ./configure --disable-decompression --enable-static
            make -j5 
            sudo make V=1 install
            tree ./
